### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by yulei-chen** [shanmiteko/wsBiliLiveComment#1]

**Comment by shanmiteko** [comment]
```sh
$ npm i bili-live-comment-ws -g
$ danmaku
```

**Comment by yulei-chen** [comment]
进场提醒怎么开呢

**Comment by shanmiteko** [comment]
目前只有显示弹幕的功能
 - [message_handle](https://github.com/shanmiteko/wsBiliLiveComment/blob/master/lib/message_handle.js)
 - [danmaku](https://github.com/shanmiteko/wsBiliLiveComment/blob/master/bin/danmaku)

**Comment by yulei-chen** [comment]
嗯 希望可以加一下这个功能

**Comment by yulei-chen** [comment]
也太快了 能更新到npm吗

**Comment by shanmiteko** [comment]
![图片](https://user-images.githubusercontent.com/87006121/139569919-4017c50f-63db-46fd-926f-9fbe122f9e99.png)
看着还行

**Comment by shanmiteko** [comment]
更新下就行了
```sh
$ sudo npm update -g
```

**Comment by yulei-chen** [comment]
太感谢了 帮了大忙！
